apiVersion: apps/v1
kind: Deployment
metadata:
  name: type-12
spec:
  replicas: 2
  selector:
    matchLabels:
      app: type-12
  template:
    metadata:
      labels:
        app: type-12
    spec:
      containers:
        - name: type-12
          image: docker.io/timattt/type-12:latest
          imagePullPolicy: Always
          env:
            - name: REACT_APP_TYPE12_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: type-6-basic-secrets
                  key: type_12_client_id
            - name: REACT_APP_TYPE12_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: type-6-basic-secrets
                  key: type_12_client_secret
            - name: REACT_APP_TYPE12_REDIRECT_URI
              value: https://messenger.shlimtech.org/code
            - name: REACT_APP_TYPE12_SERVER_IP
              value: https://service.shlimtech.org
            - name: REACT_APP_TYPE12_TYPE11_URL
              value: http://type-11.shlimtech.org
            - name: HTTPS
              value: "false"
