/**
 * @fileoverview gRPC-Web generated client stub for org.shlimtech.typeeleven
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.0-rc2
// source: messenger.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.org = {};
proto.org.shlimtech = {};
proto.org.shlimtech.typeeleven = require('./messenger_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.org.shlimtech.typeeleven.MessengerClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.org.shlimtech.typeeleven.MessengerPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.shlimtech.typeeleven.SendMessageRequest,
 *   !proto.org.shlimtech.typeeleven.SendMessageResponse>}
 */
const methodDescriptor_Messenger_sendMessage = new grpc.web.MethodDescriptor(
  '/org.shlimtech.typeeleven.Messenger/sendMessage',
  grpc.web.MethodType.UNARY,
  proto.org.shlimtech.typeeleven.SendMessageRequest,
  proto.org.shlimtech.typeeleven.SendMessageResponse,
  /**
   * @param {!proto.org.shlimtech.typeeleven.SendMessageRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.shlimtech.typeeleven.SendMessageResponse.deserializeBinary
);


/**
 * @param {!proto.org.shlimtech.typeeleven.SendMessageRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.shlimtech.typeeleven.SendMessageResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.shlimtech.typeeleven.SendMessageResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.shlimtech.typeeleven.MessengerClient.prototype.sendMessage =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.shlimtech.typeeleven.Messenger/sendMessage',
      request,
      metadata || {},
      methodDescriptor_Messenger_sendMessage,
      callback);
};


/**
 * @param {!proto.org.shlimtech.typeeleven.SendMessageRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.shlimtech.typeeleven.SendMessageResponse>}
 *     Promise that resolves to the response
 */
proto.org.shlimtech.typeeleven.MessengerPromiseClient.prototype.sendMessage =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.shlimtech.typeeleven.Messenger/sendMessage',
      request,
      metadata || {},
      methodDescriptor_Messenger_sendMessage);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.shlimtech.typeeleven.GetMessageAfterRequest,
 *   !proto.org.shlimtech.typeeleven.GetMessageAfterResponse>}
 */
const methodDescriptor_Messenger_getMessagesAfter = new grpc.web.MethodDescriptor(
  '/org.shlimtech.typeeleven.Messenger/getMessagesAfter',
  grpc.web.MethodType.UNARY,
  proto.org.shlimtech.typeeleven.GetMessageAfterRequest,
  proto.org.shlimtech.typeeleven.GetMessageAfterResponse,
  /**
   * @param {!proto.org.shlimtech.typeeleven.GetMessageAfterRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.shlimtech.typeeleven.GetMessageAfterResponse.deserializeBinary
);


/**
 * @param {!proto.org.shlimtech.typeeleven.GetMessageAfterRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.shlimtech.typeeleven.GetMessageAfterResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.shlimtech.typeeleven.GetMessageAfterResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.shlimtech.typeeleven.MessengerClient.prototype.getMessagesAfter =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.shlimtech.typeeleven.Messenger/getMessagesAfter',
      request,
      metadata || {},
      methodDescriptor_Messenger_getMessagesAfter,
      callback);
};


/**
 * @param {!proto.org.shlimtech.typeeleven.GetMessageAfterRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.shlimtech.typeeleven.GetMessageAfterResponse>}
 *     Promise that resolves to the response
 */
proto.org.shlimtech.typeeleven.MessengerPromiseClient.prototype.getMessagesAfter =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.shlimtech.typeeleven.Messenger/getMessagesAfter',
      request,
      metadata || {},
      methodDescriptor_Messenger_getMessagesAfter);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.shlimtech.typeeleven.GetMessageBeforeRequest,
 *   !proto.org.shlimtech.typeeleven.GetMessageBeforeResponse>}
 */
const methodDescriptor_Messenger_getMessagesBefore = new grpc.web.MethodDescriptor(
  '/org.shlimtech.typeeleven.Messenger/getMessagesBefore',
  grpc.web.MethodType.UNARY,
  proto.org.shlimtech.typeeleven.GetMessageBeforeRequest,
  proto.org.shlimtech.typeeleven.GetMessageBeforeResponse,
  /**
   * @param {!proto.org.shlimtech.typeeleven.GetMessageBeforeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.shlimtech.typeeleven.GetMessageBeforeResponse.deserializeBinary
);


/**
 * @param {!proto.org.shlimtech.typeeleven.GetMessageBeforeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.shlimtech.typeeleven.GetMessageBeforeResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.shlimtech.typeeleven.GetMessageBeforeResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.shlimtech.typeeleven.MessengerClient.prototype.getMessagesBefore =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.shlimtech.typeeleven.Messenger/getMessagesBefore',
      request,
      metadata || {},
      methodDescriptor_Messenger_getMessagesBefore,
      callback);
};


/**
 * @param {!proto.org.shlimtech.typeeleven.GetMessageBeforeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.shlimtech.typeeleven.GetMessageBeforeResponse>}
 *     Promise that resolves to the response
 */
proto.org.shlimtech.typeeleven.MessengerPromiseClient.prototype.getMessagesBefore =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.shlimtech.typeeleven.Messenger/getMessagesBefore',
      request,
      metadata || {},
      methodDescriptor_Messenger_getMessagesBefore);
};


module.exports = proto.org.shlimtech.typeeleven;

