version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 1s
      timeout: 1s
      retries: 100
    user: postgres
    command: ["postgres", "-c", "log_statement=all"]
  envoy:
    image: envoyproxy/envoy:dev-1ffd4522cdb86ac62ad307d8f28a166e5261411b
    ports:
      - "8080:8080"
      - "8081:8081"
      - "10000:10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      default:
  type-11:
    image: quay.io/timattt/type-11
    ports:
      - "9090:9090"
    networks:
      default:
    depends_on:
      - postgres
      - type-6
      - envoy
    environment:
      TYPE6_POSTGRES_URL: "jdbc:postgresql://postgres:5432/postgres"
      TYPE6_POSTGRES_USER: postgres
      TYPE6_POSTGRES_PASSWORD: postgres
      TYPE11_JWKS: http://type-6:7777/oauth2/jwks
      TYPE11_REACTIVE_POSTGRES_URL: "r2dbc:postgresql://postgres:5432/postgres"
      TYPE11_ACTIVE_PROFILE: "debug"
  rabbit:
    image: rabbitmq:management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    ports:
      - "15672:5672"
      - "1567:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
  redis:
    image: redis:latest
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass redis
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
  type-6:
    image: quay.io/timattt/type-6
    ports:
      - "7777:7777"
    volumes:
      - "./keys:/etc/secrets"
    environment:
      TYPE6_ENABLE_SSL: false
      TYPE6_ACTIVE_PROFILE: debug
      TYPE6_POSTGRES_USER: postgres
      TYPE6_HOST: localhost:7777
      TYPE6_POSTGRES_URL: "jdbc:postgresql://postgres:5432/postgres"
      TYPE6_POSTGRES_PASSWORD: postgres
      TYPE8_CLIENT_ID: aaa
      TYPE8_CLIENT_SECRET: aaa
      TYPE8_HOSTNAME: localhost
      TYPE8_CLIENT_REDIRECT_URI: localhost
      TYPE12_CLIENT_ID: type12-client
      TYPE12_CLIENT_SECRET: type12-secret
      TYPE12_HOSTNAME: http://localhost:3000
      TYPE12_CLIENT_REDIRECT_URI: http://localhost:3000/code
      TYPE6_RABBIT_HOST: rabbit
      TYPE6_REDIS_HOST: redis
      TYPE6_REDIS_PASSWORD: redis
      TYPE6_RABBIT_USERNAME: rabbit
      TYPE6_RABBIT_PASSWORD: rabbit
      TYPE6_GITHUB_CLIENT_ID: aaa
      TYPE6_GITHUB_CLIENT_SECRET: aaa
      TYPE6_YANDEX_CLIENT_ID: aaa
      TYPE6_YANDEX_CLIENT_SECRET: aaa
      TYPE6_WEB_RSA_PUBLIC_KEY_PATH: /etc/secrets/public_key.der
      TYPE6_WEB_RSA_PRIVATE_KEY_PATH: /etc/secrets/private_key.der
    depends_on:
      - postgres
      - rabbit
      - redis
networks:
  default: